blog/urls.py
from django.urls import path
from . import views
from .views import robots_txt

urlpatterns = [path("", views.PostView.as_view()),
               path('dostavka/', views.Dostavka.as_view()),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>', views.AddComents.as_view(), name='add_comments'),
               path('<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
               path('<int:pk>/del_likes', views.DelLike.as_view(), name='dell_likes'),
               path("robots.txt", robots_txt)]




myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from urllib import request
from django.db import models
from django.shortcuts import render


# Create your models here.
class Post(models.Model):
    '''даные о посте'''
    title = models.CharField('Заголовок записи', max_length=100)
    description = models.TextField("Текст записи")
    author = models.CharField('Автор', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')
    views = models.IntegerField()
   
    

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    email = models.EmailField()
    telefon = models.CharField('Телефон', max_length=100)
    name = models.CharField('Имя', max_length=50)
    text_comment = models.TextField('Текст комментария', max_length=200)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)
    

    def __str__(self):
        return f'{self.name}, {self.text_comment}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''Лайки'''
    ip = models.CharField('IP адрес', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)



class Visit(models.Model):
    ip_addr = models.CharField("Ip", max_length=50)
    count = models.IntegerField(default=0)
    data = models.CharField("Data", max_length=50)

    '''выводит в админку поля обекта'''
    def __str__(self):
        return f'{"IP адрес: "+self.ip_addr+" | | "},{" Количество : "+str(self.count)}, {" | | Дата: "+self.data}'

    class Meta:
        verbose_name = 'Посетители:'
        verbose_name_plural = 'Гости сайта'


   

blog/views.py
from venv import logger
from django.shortcuts import render, redirect
from django.views.generic.base import View
from simple_search import search_filter
from .models import Post

from django.http import HttpResponse
from django.views.decorators.http import require_GET
from .form import CommentsForm
from .models import Post, Likes, Visit
from datetime import datetime


class PostView(View):
    '''Вывод записей'''

    def get(self, request):
    
     try:
        ip = get_client_ip(request)
        '''Получаем обескт с базы, по полученому ip, якшо нема в базе то созд. новый '''
        visits = Visit.objects.get(ip_addr = ip)
        visits.data = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        visits.count += 1
        visits.save()
        visits = Visit.objects.all()
     except:
         '''создается новый обект'''
         visit = Visit()
         visit.count += 1
         visit.ip_addr = ip
         visit.data = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
         visit.save()
         visits = Visit.objects.all()
            
     posts = Post.objects.all().order_by('-id')
     return render(request, "blog/blog.html", {'post_list': posts, 'visits': visits})

class Dostavka(View):
    '''Доставка'''
    def get(self, request):
        return render(request, "blog/dostavka.html")


@require_GET
def robots_txt(request):
    lines = [
        "User-Agent: *",
        "Disallow: /admin/",
        "Disallow: /admin",
        "Disallow: /private/",
        "Disallow: /junk/",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

class PostDetail(View):
    '''отдельная страница для записи'''

    def get(self, request, pk):
        
        post = Post.objects.get(id=pk)
        post.views +=1
        post.save()
        return render(request, 'blog/blog_detail.html', {'post': post})


class AddComents(View):
    '''Добавление комментариев'''

    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect('/')


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip



class AddLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')


class DelLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client)
            lik.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

templates/blog/blog.html
{% load static %}
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
	<title>Барахолка:)</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href=" {% static '/css/style.css' %} ">

</head>

<body>
 <div class="topnav">
  <a class="active" href="#home">Главная
  <a href="/dostavka">Доставка</a>
    <a href="#contact"style="color:red">
      <span>
      <a href="tel:+39998887766" style="color:red;">+3(999)888-77-66</a>
      </span>
    </a>
    <a href="/admin" id="loginLink">online</a>
 </div>

<div class="row">
  <div class="leftcolumn">
    {% for post in post_list %}
    <div class="card">
      <h1><a href="{{ post.id }}" style="color:green">{{ post.title }}</a></h1>
      <div class="description">
      <div class="fakeimg">
        <img src="{{ post.img.url }}"/>
      </div>
        <p><h2><a href="{{ post.id }}">{{ post.description|truncatechars:150 }}</a></h2></p>
      </div>
      <div class="views">
        {{ post.views }}
        <img src="/media/aice.png"/>
      </div>
      <p><a href="" style="color:red"> цена <h1>{{ post.author }}</h1></a></p>
    </div>
    {% endfor %}
  </div>
</div>

</body>
</html>

templates/blog/blog_detail.html
{% load static %}
<html >
<head>
   <title>Газоблок</title>
   <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
   <link rel="stylesheet" type="text/css" href=" {% static '/css/style.css' %} ">
</head>
<body>
 <div class="shell">
	<div class="border">

		<div class="topnav">
  <a class="" href="/">Главнвя</a>
  <a class="active" href="#">{{ post.title|truncatechars:10 }} </a>
  <a href="/dostavka">Доставка</a>
      </div>

		<div id="main">
   			<div id="content" class="left">

      			<div class="projects">
         			   <p style="font-size: 30px; color: blue; text-align: center;"> {{ post.title }} </p>
         			   <br>
                  <p align="center">
                    <img src="{{ post.img.url }}" width="50%"/>
                  </p>
         			<div class="item">
						<div class="text-left">
               				<p style="font-family: verdana; font-size: 28px; font-align: center">{{ post.description }}</p>
               				<p>тел. 050-020-36-91</p>
            			</div>
            			<div class="cl"> </div>
         			</div>
     			 </div>
   			</div>
			<div>
				<a href="{% url 'add_likes' post.id %}">Нравится {{ post.likes_set.all.count }}</a>

			</div>
			<div class="form-comment">
				<p style="font-size: 30px; text-align: center">Оформить заказ</p>
				<div>
					<form action="{% url 'add_comments' post.id %}" method="post">
						{% csrf_token %}
						<div>
							<label>Ваш комментарий к заказу:</label>
							<textarea name="text_comment"></textarea>
						</div>
						<div>
							<label><p style="font-size:30px;">Ваше имя *</p></label>
							<input type="text" name="name">
						</div>
						<div>
							<label><p style="font-size:30px;">Ваш email *</p></label>
							<input type="email" name="email">
						</div>
						<div>
							<label><p style="font-size:30px;">Ваш телефон *</p></label>
							<input type="text" name="telefon">
						</div>
						<div><button type="submit"><p style="font-size:30px;">Отправиь</p></button></div>
					</form>
				</div>
			</div>
			<div>

				<div class="view-comment">
					<h4></h4>
					<p>

					</p>
				</div>

			</div>


			<div class="cl"> </div>
		</div>

	</div>
</div>

</body>
</html>

templates/blog/dostavka.html
{% load static %}
<html >
<head>
    <title>ShopTorg - Поставщик Стройматериалов (Березань)</title>
     <meta description="Поставщик Стройматериалов (Березань)"><meta property="og:type" content="website"/>
   <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
   <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
    <meta name="google-site-verification" content="lkpjCYkRU5UyHErb1NYbJafXQVyPsMY-WWwvwYHqfg8" />
   <title>ShopTorg - Поставщик Стройматериалов (Березань)</title>
   <meta property="og:url" content="https://shoptorg.pythonanywhere.com"/>
   <meta property="og:title" content="ShopTorg Строй материалы"/><meta property="og:description" content="Поставщик Стройматериалов (Березань)"/>
   <meta name="keywords" content="магазин стройматериалов, Березань, область Борисполь, яготин, Киев, дешево, доставка, аэрок, Березань, Борисполь, яготин, ShopTorg: Бетонний блок, Цегла, Керамічний блок, Газобетонний блок, строй материалы, Будівельні суміші, Шпаклівка, Штукатурка, Цемент, Гіпсокартон, Металлопрокат, проф настил, есть доставка, ШЛАКОБЛОК ,БАЗАЛЬТОВАЯ ВАТА, Профіль для гіпсокартону, Покрівля, металочерепиця, Доставка по всей Украине, Украина доставка ">
   <meta property="og:title" content="Ціна на Газоблоки, Піноблок, Газобетон у Ровенську зону аерок Обухів Березань: продаж, ціна в Києві. блоки стінові від; Soptorg: газобетон і газоблок за оптовою ціною"/>
            <meta property="og:description" content="Ціна на Газоблоки, Піноблок, Газобетон у Рівній зоні аерок аерок Обухов Березань. Докладна інформація про товар/заслуг і постачальник. Ціна та умови постачання"/>


	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
 <div class="topnav">
  <a href="/">Главная</a>
     <a class="active" href="/dostavka">Доставка</a>
  <a href="/dostavka" class="center" style="color:red;">тел. 050-999-99-99</a>
</div>

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <div class="description">

        <img src="/media/dostavka.jpg" width="400px" height="300px"/>

          <h1> <p>
              Для того чтобы купить с доставкой стройматериалы,
              позвоните нам по номеру телефону указанным на сайте.
              Можно доставить стеновые материалы кирпич, пеноблок,
              газоблок, шлакоблок манипулятором или бортовыми машинами под ручную выгрузку.
              Доставка осуществляется в удобное для клиента время.
          </p></a></h1>

      <p>{{ post.description }}</p>
      </div>
    </div>
  </div>

</div>

</body>
</html>